### PR TITLE
anongit has a sub folder to git. and gnome has /browse/ sub-folder.

### PR DESCRIPTION
**Pull request by KerwinMa**
Changed some more recipe URLs, pls check if those helps for the others.

### CODE REVIEW

**Comment by nirbheek** [comment]
These are all wrong. Read again. :)

http://cgit.freedesktop.org/gstreamer/orc/
> Clone
> **git://anongit.freedesktop.org/gstreamer/orc**
> ssh://git.freedesktop.org/git/gstreamer/orc
> http://anongit.freedesktop.org/git/gstreamer/orc.git

https://git.gnome.org/browse/seed
> git://git.gnome.org/seed
> https://git.gnome.org/browse/seed
> ssh://USERNAME@git.gnome.org/git/seed

**Comment by KerwinMa** [comment]
Any idea why I can't git clone 'git://', but I can git clone 'http://' URLs? 
Thanks.

**Comment by nirbheek** [comment]
Are you behind a proxy or on a network that doesn't allow connections to ports other than 80/443?

**Comment by KerwinMa** [comment]
In office, yes. I will try it when get home. Thanks.

**Comment by KerwinMa** [comment]
Tried the following at home, not able to clone:

git clone git://anongit.freedesktop.org/gstreamer/orc
Cloning into 'orc'...
fatal: unable to connect to anongit.freedesktop.org:
anongit.freedesktop.org[0: 131.252.210.161]: errno=No such file or directory

**Comment by nirbheek** [comment]
It works for me:

$ git clone git://anongit.freedesktop.org/gstreamer/orc
Cloning into 'orc'...
remote: Counting objects: 7234, done.
remote: Compressing objects: 100% (2218/2218), done.
remote: Total 7234 (delta 5505), reused 6530 (delta 5007)
Receiving objects: 100% (7234/7234), 1.34 MiB | 114.00 KiB/s, done.
Resolving deltas: 100% (5505/5505), done.
Checking connectivity... done.

There's something wrong on your end. :)

**Comment by KerwinMa** [comment]
yes, my windows has problem to do it. Ubuntu works:
kerwin@ubuntu:~$  git clone git://anongit.freedesktop.org/gstreamer/orc
Cloning into 'orc'...
remote: Counting objects: 7234, done.
remote: Compressing objects: 100% (2218/2218), done.
remote: Total 7234 (delta 5504), reused 6531 (delta 5007)
Receiving objects: 100% (7234/7234), 1.35 MiB | 350.00 KiB/s, done.
Resolving deltas: 100% (5504/5504), done.
Checking connectivity... done.

**Comment by KerwinMa** [comment]
thanks, will close it.

**Pull request closed without merging**
